#!/bin/bash
#====================================================
#
#====================================================
	clear
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[44;1;37m                ALTERAR DATA UTILIZADORES SSH | UUID                    \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"


    HOST="/etc/SSHPlus/RegV2ray"
    IDEUUID="$(cat $HOST|cut -d'|' -f1)"
    USERUUID="$(cat $HOST|cut -d'|' -f2)"
    DATAUUID="$(cat $HOST|cut -d'|' -f3)"

    database="/root/usuarios.db"

    echo -e "\e[97m    UTILIZADOR SSH   |               UUID                 |     DATA     \e[93m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    tput setaf 3 ; tput bold ; echo ""; echo "LISTA DE UTILIZADORES SSH | UUID E SUAS DATAS:" ; tput sgr0
    echo ""
    list_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)

    i=0
    unset _userPass
    unset _userPassUUID
    while read user hostreturn ; do
    IDEUUID=$(cat /etc/SSHPlus/RegV2ray|grep -w "$user"|cut -d'|' -f1)
    UserUuidList=$(cat /etc/SSHPlus/RegV2ray|grep -w "$user"|cut -d'|' -f2)
    DataExp=$(cat /etc/SSHPlus/RegV2ray|grep -w "$user"|cut -d'|' -f3)
    

	i=$(expr $i + 1)
	_oP=$i
	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
	expire="$(chage -l $user | grep -E "Account expires" | cut -d ' ' -f3-)"

    
	if [[ $expire == "never" ]]
	then
		echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$user\033[1;33m00/00/0000   S/DATA\033[0m"
	else
		databr="$(date -d "$expire" +"%Y%m%d")"
		hoje="$(date -d today +"%Y%m%d")"
		if [ $hoje -ge $databr ]
		then
			i_user=$(echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$user\033[1;37m")

			datanormal="$(echo -e "\033[1;31m$(date -d"$expire" '+%d/%m/%Y')")"
			expired=$(echo -e "\033[1;31mVENCEU\033[0m")
			printf '%-62s%-20s%s\n' "$i_user" "$IDEUUID" "$datanormal" "$expired"
			echo "exp" > /tmp/exp
		else
			i_user=$(echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$user\033[1;37m")
            
			datanormal="$(echo -e "\033[1;33m$(date -d"$expire" '+%d/%m/%Y')")"
			ative=$(echo -e "\033[1;32mVALIDO\033[0m")
			printf '%-62s%-20s%s\n' "$i_user" "$IDEUUID" "$datanormal" "$ative"
		fi
	fi
	_userPass+="\n${_oP}:${user}"
    _userPassUUID+="\n${_oP}:${IDEUUID}"
    _usuarioUUID+="\n${_oP}:${UserUuidList}"
    _userUuidDATA+="\n${_oP}:${DataExp}"
done <<< "${list_user}"
tput sgr0
echo ""
if [ -a /tmp/exp ]
then
	rm /tmp/exp
fi

num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
echo -ne "\033[1;32mDIGITE UM NÚMERO OU UTILIZADOR SSH \033[1;33m[\033[1;36m1\033[1;33m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
if [[ -z $option ]]
then
	echo ""
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "Erro,  Nome do utilizador vazio ou inválido! " ; tput sgr0
    echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
    exit
fi
usuario=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
usuarioUUIDid=$(echo -e "${_userPassUUID}" | grep -E "\b$option\b" | cut -d: -f1)
UUID=$(echo -e "${_userPassUUID}" | grep -E "\b$option\b" | cut -d: -f2)
usuarioUUID=$(echo -e "${_usuarioUUID}" | grep -E "\b$option\b" | cut -d: -f2)
usuaroUuidDATA=$(echo -e "${_userUuidDATA}" | grep -E "\b$option\b" | cut -d: -f2)

if [[ -z $usuario ]]
then
	echo ""
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "Erro,  Nome do utilizador vazio ou inválido!!! " ; tput sgr0
    echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
    echo ""
	exit
else
	if [[ `grep -c /$usuario: /etc/passwd` -ne 0 ]]
	then
	    echo ""
	    echo -e "\033[1;31mEX:\033[1;33m(\033[1;32mDATA: \033[1;37mDIA/MÊS/ANO \033[1;33mOU \033[1;32mDIAS: \033[1;37m30 - 60 - 90\033[1;33m)"
	    #echo "SSH"
        #echo "$usuario"
        #echo "-----"
        #echo "UUID"
        #echo "$usuarioUUIDid"
        #echo "$UUID"
        #echo "$usuarioUUID"
        #echo "$usuaroUuidDATA"
	    echo -ne "\033[1;32mNova data ou dias para o utilizador \033[1;33m$usuario: \033[1;37m"; read inputdate
	    if [[ "$(echo -e "$inputdate" | grep -c "/")" = "0" ]]; then 
	    	udata=$(date "+%d/%m/%Y" -d "+$inputdate days")
	    	sysdate="$(echo "$udata" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
	    else
	    	udata=$(echo -e "$inputdate")
	    	sysdate="$(echo "$inputdate" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
	    fi
		if (date "+%Y-%m-%d" -d "$sysdate" > /dev/null  2>&1)
		then
			if [[ -z $inputdate ]]
			then
				echo ""
				tput setaf 7 ; tput setab 1 ; tput bold ;	echo "Digitou uma data inválida ou inexistente!" ; echo "Digite uma data válida no formato DIA/MÊS/ANO " ; echo "Por exemplo: 21/04/2030" ; tput sgr0 ; tput sgr0
				echo ""	
                echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
                echo ""
				exit
			else
				if (echo $inputdate | egrep [^a-zA-Z] &> /dev/null)
				then
					today="$(date -d today +"%Y%m%d")"
					timemachine="$(date -d "$sysdate" +"%Y%m%d")"
					if [ $today -ge $timemachine ]
					then
						echo ""
						tput setaf 7 ; tput setab 1 ; tput bold ;	echo "Digitou uma data passada ou o dia atual!" ; echo "Digite uma data futura e válida no formato DIA/MÊS/ANO" ; echo "Por exemplo: 21/04/2030" ; tput sgr0
						echo ""
                        echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
                        echo ""
						exit
					else
						chage -E $sysdate $usuario
                        #chage -E $sysdate $UUID
                        #echo "  $UUID | $usuarioUUID | $sysdate "
                        #echo "  $UUID | $nick | $sysdate " >> /etc/SSHPlus/RegV2ray
                        #Fecha=`date +%d-%m-%y-%R`
                        #cp /etc/SSHPlus/RegV2ray /etc/SSHPlus/v2ray/RegV2ray-"$Fecha"
                        #v2ray restart > /dev/null 2>&1
						#echo "$sysdate"
                        #echo "$usuario"
						tput setaf 7 ; tput setab 4 ; tput bold ; echo "Sucesso o utilizador $usuario nova data: $udata " ; tput sgr0
                        #tput setaf 7 ; tput setab 4 ; tput bold ; echo "Sucesso o utilizador $usuarioUUID nova data: $udata " ; tput sgr0
                        echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
                        echo ""
						exit
					fi
				else
					echo ""
					tput setaf 7 ; tput setab 1 ; tput bold ;	echo "Digitou uma data inválida ou inexistente!" ; echo "Digite uma data válida no formato DIA/MÊS/ANO" ; echo "Por exemplo: 21/04/2030" ; tput sgr0
					echo ""
                    echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
                    echo ""
					exit
				fi
			fi
		else
			echo ""
			tput setaf 7 ; tput setab 1 ; tput bold ;	echo "Digitou uma data inválida ou inexistente!" ; echo "Digite uma data válida no formato DIA/MÊS/ANO" ; echo "Por exemplo: 21/04/2030" ; tput sgr0
			echo ""
            echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
            echo ""
			exit 
		fi
	else
		echo " "
		tput setaf 7 ; tput setab 1 ; tput bold ;	echo "O utilizador $usuario não existe!" ; tput sgr0
		echo " "
        echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     	echo ""
		exit
	fi

fi